version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend: 
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    env_file:
      - ./backend/.env
    depends_on:
      - mongo
    ports:
      - "3000 : 3000"

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    restart: always
    ports:
      - "80 : 80"
    depends_on:
      - backend

volumes:
  mongo_data: